"""Reads the required data from the yaml configuration file in path"""

from pathlib import Path as path
import yaml


def load_settings(config_file_path: path = path("config.yml")) -> dict:
    """Gets the login information from the configuration file provided as a pathlib object"""

    with open(config_file_path) as config_file:
        settings = yaml.safe_load(config_file)

    return settings

def get_login_info(settings: dict) -> dict:
    """Gets the login information from settings dictionary generated by load_settings()"""

    return settings["login_info"]

def get_urls(settings: dict) -> dict:
    """Gets all URLs settings dictionary generated by load_settings()"""

    return settings["url"]

def requires_completion(link_name: str, urls: dict) -> bool:

    """Checks if the configuration string requires a completion
    from the completion section of the configuration file."""

    return not urls[f"{link_name}"]["complete"]

def get_url_completion_values(settings: dict) -> dict:
    """Gets all URLs completion values dictionary generated by load_settings()"""

    return settings["url_completion_values"]


if __name__ == "__main__":
    settings = load_settings()
    urls = get_urls(settings)

    print(get_login_info(settings),3*'\n',get_urls(settings),3*'\n',get_url_completion_values(settings))
