login_info:
  login_email: 
  password: 

url:
  main_endpoint_url: https://fantasy.premierleague.com/api/
  general_information_endpoint_path: bootstrap-static/
  fixtures_url_endpoint_path: fixtures?event:{event}
  player_detailed_data_endpoint_path:  element-summary/{element_id}/
  live_gw_data_endpoint_path: event/{event_id}/live/
  fpl_manager_basic_information: entry/{fpl_manager_id}/
  fpl_manager_history: entry/{fpl_manager_id}/history
  classic_league_standings: leagues-classic/{classic_league_id}/standings

url_completion_values:
  list: 12
  element_id: 4
  event_id: 1
  fpl_manager_id: 
  classic_league_id: 

fixtures_url_parameters:
  all: 0
  future: 1
  gw: None # Can specify GW number - implement in code 

# for big public leagues - may need "standings?page_standings=2" at the end to reach second page of standings